### ISSUE TITLE
发现它不支持 eruda 的 defaults ?

### ISSUE THREAD

**Issue by alianggitok** [XiongAmao/vue-cli-plugin-eruda#8]
按照 [eruda api文档](https://github.com/liriliri/eruda/blob/master/doc/API.md) 里提供的api,好像defaults无效:
```
  pluginOptions: {
    eruda: {
      enable: debugToolEnabled,
      defaults: {
        theme: 'Monokai Pro'
      }
    }
  }
```
可否添加支持?

**Comment by XiongAmao** [comment]
`defaults`配置已更新到 v1.4.0。
需要注意如果项目内已使用eruda，eruda会在开发域名下通过`localStorage`留下了配置选项，导致你在`vue.config.js`设置的默认值不生效。如果发现更改主题/字体无效，尝试清理掉`localStorage`中eruda配置项即可解决。
